import { DEFAULT_AI_MODEL_CONFIGS } from '../../src/lib/kainbu/models.js';

export const WORKSPACE_AI_MODELS = DEFAULT_AI_MODEL_CONFIGS;
export const WORKSPACE_AI_MAX_TOKENS = 60_000;
export const WORKSPACE_AI_READ_MAX_CHARS = 12_000;
export const WORKSPACE_AI_WEB_SEARCH_MODEL = "x-ai/grok-4.1-fast";
export const WORKSPACE_AI_WEB_SEARCH_MAX_TOKENS = 2048;

export const WORKSPACE_AI_ADD_TASKS_MAX_TITLES = 10;
export const WORKSPACE_AI_DELETE_TASKS_MAX_REFS = 10;
export const WORKSPACE_AI_UPDATE_TASK_MAX_CHARS = 8_000;
export const WORKSPACE_AI_MAX_TOOL_CALLS = 12;
export const WORKSPACE_AI_MAX_BOARD_MUTATIONS = 15;
export const WORKSPACE_AI_MAX_ADD_TASKS_CALLS = 4;
export const WORKSPACE_AI_MAX_UPDATE_TASK_CALLS = 10;
export const WORKSPACE_AI_MAX_DELETE_TASK_CALLS = 4;
export const WORKSPACE_AI_MAX_MODEL_TURNS = 3;
export const WORKSPACE_AI_MAX_MODEL_TURNS_LARGE_BOARD = 5;
export const WORKSPACE_AI_STREAM_DELTA_THROTTLE_MS = 50;
export const WORKSPACE_AI_BOARD_INDEX_MAX_LINES = 120;
export const WORKSPACE_AI_BOARD_LIST_TASKS_DEFAULT_LIMIT = 15;
export const WORKSPACE_AI_TURN_NOTE_MAX_CHARS = 400;
export const WORKSPACE_AI_PROMPT_CACHE_ENABLED = process.env.WORKSPACE_AI_PROMPT_CACHE !== "0";
