import * as esbuild from 'esbuild';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

await esbuild.build({
	entryPoints: [resolve(root, 'server/vercel-entry.ts')],
	outfile: resolve(root, 'api/index.js'),
	bundle: true,
	platform: 'node',
	target: 'node22',
	format: 'esm',
	packages: 'bundle',
	sourcemap: true,
	banner: {
		js: '// Generated by scripts/build-api.mjs — do not edit by hand.'
	},
	logLevel: 'info'
});

console.log('Built api/index.js for Vercel');
